---
apiVersion: v1
kind: Service
metadata:
  name: compose-post-service
  labels:
    death-star-project: social-network
    app: compose-post-service
  namespace: social-network
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: compose-post-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compose-post-service
  labels:
    death-star-project: social-network
    app: compose-post-service
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: compose-post-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: compose-post-service
      name: compose-post-service
    spec:
      containers:
      - name: compose-post-service
        image: yg397/social-network-microservices
        command: ["ComposePostService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
          - mountPath: /social-network-microservices/config/service-config.json
            subPath: service-config.json
            name: service-conf-json
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
        - name: service-conf-json
          configMap:
            name: service-config-json
